export const seedData = {
  categories: [
    {
      id: "cat-fiction",
      slug: "fiction",
      icon: "📚",
      accent: "linear-gradient(135deg,#f2ebff 0%,#ffffff 100%)",
      name: { ru: "Классика и художественная", uz: "Badiiy adabiyot", en: "Fiction & classics" },
      description: { ru: "Романы, проза и мировая классика", uz: "Romanlar va jahon klassikasi", en: "Novels, prose and classics" },
    },
    {
      id: "cat-business",
      slug: "business",
      icon: "💼",
      accent: "linear-gradient(135deg,#efe9ff 0%,#fff8fb 100%)",
      name: { ru: "Бизнес", uz: "Biznes", en: "Business" },
      description: { ru: "Маркетинг, менеджмент, деньги", uz: "Marketing, menejment, moliya", en: "Marketing, management, money" },
    },
    {
      id: "cat-psychology",
      slug: "psychology",
      icon: "🧠",
      accent: "linear-gradient(135deg,#f6edff 0%,#fff 100%)",
      name: { ru: "Психология", uz: "Psixologiya", en: "Psychology" },
      description: { ru: "Эмоции, мышление и отношения", uz: "Hissiyotlar va tafakkur", en: "Emotions, thinking and relationships" },
    },
    {
      id: "cat-children",
      slug: "children",
      icon: "🧒",
      accent: "linear-gradient(135deg,#fff0ff 0%,#fff 100%)",
      name: { ru: "Детские", uz: "Bolalar", en: "Children" },
      description: { ru: "Сказки, комиксы, подростковое", uz: "Ertaklar va bolalar kitoblari", en: "Fairy tales and young readers" },
    },
    {
      id: "cat-history",
      slug: "history",
      icon: "🏛️",
      accent: "linear-gradient(135deg,#f3efff 0%,#ffffff 100%)",
      name: { ru: "История", uz: "Tarix", en: "History" },
      description: { ru: "Цивилизации и биографии", uz: "Sivilizatsiyalar va biografiyalar", en: "Civilisations and biographies" },
    },
    {
      id: "cat-selfdev",
      slug: "self-dev",
      icon: "🚀",
      accent: "linear-gradient(135deg,#ece8ff 0%,#ffffff 100%)",
      name: { ru: "Саморазвитие", uz: "O'zini rivojlantirish", en: "Self development" },
      description: { ru: "Привычки и личная эффективность", uz: "Odatlar va samaradorlik", en: "Habits and productivity" },
    },
  ],
  authors: [
    { id: "a1", slug: "mikhail-bulgakov", name: "Михаил Булгаков", country: "Российский", booksCount: 12, avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=300&h=300&fit=crop", accent: "#6f35ff" },
    { id: "a2", slug: "fyodor-dostoevsky", name: "Фёдор Достоевский", country: "Российский", booksCount: 18, avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=300&h=300&fit=crop", accent: "#6f35ff" },
    { id: "a3", slug: "james-clear", name: "Джеймс Клир", country: "Американский", booksCount: 2, avatar: "https://images.unsplash.com/photo-1507591064344-4c6ce005b128?w=300&h=300&fit=crop", accent: "#6f35ff" },
    { id: "a4", slug: "yuval-noah-harari", name: "Юваль Ной Харари", country: "Израильский", booksCount: 4, avatar: "https://images.unsplash.com/photo-1504257432389-52343af06ae3?w=300&h=300&fit=crop", accent: "#6f35ff" },
    { id: "a5", slug: "leo-tolstoy", name: "Лев Толстой", country: "Российский", booksCount: 24, avatar: "https://images.unsplash.com/photo-1552058544-f2b08422138a?w=300&h=300&fit=crop", accent: "#6f35ff" },
    { id: "a6", slug: "jk-rowling", name: "Дж. К. Роулинг", country: "Британская", booksCount: 8, avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=300&h=300&fit=crop", accent: "#6f35ff" },
  ],
  products: [
    {
      id: "p-atomic-habits",
      source: "seed",
      slug: "atomic-habits",
      title: "Атомные привычки",
      author: "Джеймс Клир",
      authorSlug: "james-clear",
      price: 125000,
      oldPrice: 149000,
      rating: 4.7,
      reviewsCount: 2341,
      stock: 89,
      inStock: true,
      published: true,
      categorySlug: "self-dev",
      categoryName: "Саморазвитие",
      language: "Русский",
      publisher: "Альпина Паблишер",
      isbn: "978-5-9614-3534-5",
      coverType: "Твёрдый переплёт",
      pages: 320,
      year: 2023,
      description: "Практическое руководство по формированию хороших привычек и избавлению от плохих. Книга объясняет, как небольшие изменения поведения постепенно дают ощутимый результат в работе, учёбе и личной жизни.",
      summary: "Проверенная система маленьких изменений, дающих большие результаты.",
      images: ["https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=800&h=1000&fit=crop"],
      format: "60x90/16",
      weight: "380 г",
      featured: { bestseller: true, newArrival: true, collectionSlugs: ["business-boost", "smart-reading"] },
    },
    {
      id: "p-sapiens",
      source: "seed",
      slug: "sapiens",
      title: "Sapiens: Краткая история человечества",
      author: "Юваль Ной Харари",
      authorSlug: "yuval-noah-harari",
      price: 98000,
      oldPrice: null,
      rating: 4.8,
      reviewsCount: 3102,
      stock: 42,
      inStock: true,
      published: true,
      categorySlug: "history",
      categoryName: "История",
      language: "Русский",
      publisher: "Синдбад",
      isbn: "978-5-00131-074-5",
      coverType: "Твёрдый переплёт",
      pages: 520,
      year: 2024,
      description: "Масштабный взгляд на историю человечества от когнитивной революции до мира алгоритмов. Книга помогает иначе посмотреть на культуру, религию, деньги и технологии.",
      summary: "Путешествие по ключевым этапам развития человека и общества.",
      images: ["https://images.unsplash.com/photo-1512820790803-83ca734da794?w=800&h=1000&fit=crop"],
      format: "70x100/16",
      weight: "430 г",
      featured: { bestseller: true, collectionSlugs: ["smart-reading"] },
    },
    {
      id: "p-master-and-margarita",
      source: "seed",
      slug: "master-and-margarita",
      title: "Мастер и Маргарита",
      author: "Михаил Булгаков",
      authorSlug: "mikhail-bulgakov",
      price: 89000,
      oldPrice: 115000,
      rating: 4.9,
      reviewsCount: 1247,
      stock: 27,
      inStock: true,
      published: true,
      categorySlug: "fiction",
      categoryName: "Художественная литература",
      language: "Русский",
      publisher: "АСТ",
      isbn: "978-5-17-090152-5",
      coverType: "Твёрдый переплёт",
      pages: 480,
      year: 2023,
      description: "Один из самых известных романов русской литературы XX века. Мистическая Москва, философские диалоги и история любви, которую читают снова и снова.",
      summary: "Классика, которая одинаково сильна как роман о любви и как роман о свободе.",
      images: ["https://images.unsplash.com/photo-1476275466078-4007374efbbe?w=800&h=1000&fit=crop"],
      featured: { bestseller: true, collectionSlugs: ["classic-evenings"] },
    },
    {
      id: "p-little-prince",
      source: "seed",
      slug: "little-prince",
      title: "Маленький принц",
      author: "Антуан де Сент-Экзюпери",
      price: 65000,
      oldPrice: 82000,
      rating: 4.9,
      reviewsCount: 4521,
      stock: 53,
      inStock: true,
      published: true,
      categorySlug: "children",
      categoryName: "Детские книги",
      language: "Русский",
      publisher: "Эксмо",
      isbn: "978-5-04-098820-4",
      coverType: "Твёрдый переплёт",
      pages: 96,
      year: 2024,
      description: "Тонкая философская сказка о дружбе, любви и ответственности. Подходит и детям, и взрослым читателям.",
      summary: "Одна из самых цитируемых книг о том, что действительно важно.",
      images: ["https://images.unsplash.com/photo-1495446815901-a7297e633e8d?w=800&h=1000&fit=crop"],
      featured: { bestseller: true, collectionSlugs: ["kids-favorites", "classic-evenings"] },
    },
    {
      id: "p-rich-dad",
      source: "seed",
      slug: "rich-dad-poor-dad",
      title: "Богатый папа, бедный папа",
      author: "Роберт Кийосаки",
      price: 72000,
      oldPrice: 95000,
      rating: 4.7,
      reviewsCount: 1876,
      stock: 31,
      inStock: true,
      published: true,
      categorySlug: "business",
      categoryName: "Бизнес",
      language: "Русский",
      publisher: "Попурри",
      isbn: "978-985-15-4373-0",
      coverType: "Мягкий переплёт",
      pages: 352,
      year: 2023,
      description: "Бестселлер о финансовой грамотности и взгляде на деньги через призму активов, обязательств и личной ответственности.",
      summary: "Простое объяснение сложных финансовых привычек и денежных моделей мышления.",
      images: ["https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=800&h=1000&fit=crop"],
      featured: { bestseller: true, collectionSlugs: ["business-boost"] },
    },
    {
      id: "p-1984",
      source: "seed",
      slug: "1984",
      title: "1984",
      author: "Джордж Оруэлл",
      price: 68000,
      oldPrice: null,
      rating: 4.8,
      reviewsCount: 3204,
      stock: 22,
      inStock: true,
      published: true,
      categorySlug: "fiction",
      categoryName: "Художественная литература",
      language: "Русский",
      publisher: "АСТ",
      isbn: "978-5-17-080249-4",
      coverType: "Мягкий переплёт",
      pages: 320,
      year: 2024,
      description: "Антиутопический роман о тотальном контроле, правде и памяти. Одна из самых актуальных книг о власти и страхе.",
      summary: "Книга, к которой возвращаются каждый раз, когда мир меняется слишком быстро.",
      images: ["https://images.unsplash.com/photo-1516979187457-637abb4f9353?w=800&h=1000&fit=crop"],
      featured: { newArrival: true, collectionSlugs: ["classic-evenings"] },
    },
    {
      id: "p-idiot",
      source: "seed",
      slug: "idiot",
      title: "Идиот",
      author: "Фёдор Достоевский",
      authorSlug: "fyodor-dostoevsky",
      price: 75000,
      oldPrice: null,
      rating: 4.7,
      reviewsCount: 892,
      stock: 16,
      inStock: true,
      published: true,
      categorySlug: "fiction",
      categoryName: "Художественная литература",
      language: "Русский",
      publisher: "АСТ",
      isbn: "978-5-17-146557-6",
      coverType: "Твёрдый переплёт",
      pages: 640,
      year: 2023,
      description: "История князя Мышкина и попытки остаться добрым человеком в мире страстей, тщеславия и внутреннего надлома.",
      summary: "Достоевский в мощном издании для вдумчивого чтения.",
      images: ["https://images.unsplash.com/photo-1541963463532-d68292c34b19?w=800&h=1000&fit=crop"],
      featured: { bestseller: true, collectionSlugs: ["classic-evenings"] },
    },
    {
      id: "p-thinking-fast",
      source: "seed",
      slug: "thinking-fast-and-slow",
      title: "Думай медленно, решай быстро",
      author: "Даниэль Канеман",
      price: 99000,
      oldPrice: 120000,
      rating: 4.8,
      reviewsCount: 2198,
      stock: 18,
      inStock: true,
      published: true,
      categorySlug: "psychology",
      categoryName: "Психология",
      language: "Русский",
      publisher: "АСТ",
      isbn: "978-5-17-080053-7",
      coverType: "Твёрдый переплёт",
      pages: 653,
      year: 2023,
      description: "Книга о двух системах мышления: быстрой интуитивной и медленной аналитической. Объясняет, почему мы ошибаемся и как принимать более сильные решения.",
      summary: "Фундаментальная книга о когнитивных искажениях и принятии решений.",
      images: ["https://images.unsplash.com/photo-1506880018603-83d5b814b5a6?w=800&h=1000&fit=crop"],
      featured: { collectionSlugs: ["smart-reading"] },
    },
    {
      id: "p-harry-potter",
      source: "seed",
      slug: "harry-potter-1",
      title: "Гарри Поттер и философский камень",
      author: "Дж. К. Роулинг",
      authorSlug: "jk-rowling",
      price: 76000,
      oldPrice: null,
      rating: 4.9,
      reviewsCount: 5630,
      stock: 47,
      inStock: true,
      published: true,
      categorySlug: "children",
      categoryName: "Детские книги",
      language: "Русский",
      publisher: "Махаон",
      isbn: "978-5-389-07435-4",
      coverType: "Твёрдый переплёт",
      pages: 432,
      year: 2024,
      description: "Первая книга о мальчике-волшебнике, которая запускает большое путешествие в мир Хогвартса, дружбы и магии.",
      summary: "Семейный бестселлер, который покупают детям и возвращают в личную библиотеку взрослые.",
      images: ["https://images.unsplash.com/photo-1512820790803-83ca734da794?w=800&h=1000&fit=crop&sat=-10"],
      featured: { newArrival: true, collectionSlugs: ["kids-favorites"] },
    },
    {
      id: "p-psychology-of-influence",
      source: "seed",
      slug: "psychology-of-influence",
      title: "Психология влияния",
      author: "Роберт Чалдини",
      price: 78000,
      oldPrice: 95000,
      rating: 4.6,
      reviewsCount: 1460,
      stock: 15,
      inStock: true,
      published: true,
      categorySlug: "psychology",
      categoryName: "Психология",
      language: "Русский",
      publisher: "Питер",
      isbn: "978-5-4461-0549-1",
      coverType: "Мягкий переплёт",
      pages: 416,
      year: 2024,
      description: "Классика о принципах убеждения: взаимность, дефицит, социальное доказательство, авторитет и другие механики, которые ежедневно влияют на поведение людей.",
      summary: "Для маркетологов, продавцов и всех, кто хочет понимать решения людей глубже.",
      images: ["https://images.unsplash.com/photo-1516979187457-637abb4f9353?w=800&h=1000&fit=crop&sat=15"],
      featured: { newArrival: true, collectionSlugs: ["business-boost", "smart-reading"] },
    }
  ],
  collections: [
    {
      id: "col-1",
      slug: "business-boost",
      title: { ru: "Книги для роста в карьере", uz: "Karyera uchun kitoblar", en: "Career growth reads" },
      subtitle: { ru: "Бизнес", uz: "Biznes", en: "Business" },
      description: { ru: "Подборка про деньги, личную эффективность, влияние и управленческие навыки.", uz: "Pul, samaradorlik va boshqaruv ko'nikmalari haqida tanlov.", en: "A curated set on money, productivity, influence and management." },
      accent: "linear-gradient(135deg,#efe7ff 0%,#fef9ff 100%)",
      image: "https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?w=900&h=700&fit=crop",
      productSlugs: ["atomic-habits", "rich-dad-poor-dad", "psychology-of-influence"],
    },
    {
      id: "col-2",
      slug: "kids-favorites",
      title: { ru: "Детям и подросткам", uz: "Bolalar va o'smirlar", en: "For kids and teens" },
      subtitle: { ru: "Для детей", uz: "Bolalar", en: "Children" },
      description: { ru: "Лёгкие книги, которые можно подарить и читать всей семьёй.", uz: "Butun oila bilan o'qish mumkin bo'lgan sovg'abop kitoblar.", en: "Gift-ready books that work for the whole family." },
      accent: "linear-gradient(135deg,#f4efff 0%,#fff 100%)",
      image: "https://images.unsplash.com/photo-1507842217343-583bb7270b66?w=900&h=700&fit=crop",
      productSlugs: ["little-prince", "harry-potter-1"],
    },
    {
      id: "col-3",
      slug: "classic-evenings",
      title: { ru: "Классика на вечер", uz: "Klassika oqshomlari", en: "Evening classics" },
      subtitle: { ru: "Классика", uz: "Klassika", en: "Classics" },
      description: { ru: "Тексты, к которым хочется возвращаться — для дома, подарка и личной библиотеки.", uz: "Uy kutubxonasi va sovg'a uchun qayta o'qiladigan klassika.", en: "Timeless books you return to for home shelves and gifts." },
      accent: "linear-gradient(135deg,#f6f0ff 0%,#fff 100%)",
      image: "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=900&h=700&fit=crop&sat=10",
      productSlugs: ["master-and-margarita", "little-prince", "idiot", "1984"],
    },
    {
      id: "col-4",
      slug: "smart-reading",
      title: { ru: "Умное чтение", uz: "Aqlli o'qish", en: "Smart reading" },
      subtitle: { ru: "Психология", uz: "Psixologiya", en: "Psychology" },
      description: { ru: "Книги, которые помогают думать яснее, спорить сильнее и смотреть шире.", uz: "Tafakkur va qaror qabul qilishni kuchaytiradigan kitoblar.", en: "Books that sharpen thinking and widen your perspective." },
      accent: "linear-gradient(135deg,#ede8ff 0%,#fff 100%)",
      image: "https://images.unsplash.com/photo-1495446815901-a7297e633e8d?w=900&h=700&fit=crop&sat=5",
      productSlugs: ["atomic-habits", "sapiens", "thinking-fast-and-slow", "psychology-of-influence"],
    }
  ],
  reviews: [
    { id: "r1", customerName: "Тимур Рашидов", city: "Ташкент", dateLabel: "Март 2024", rating: 5, text: "Заказываю уже несколько лет. Удобный каталог, нормальные цены и понятная оплата." },
    { id: "r2", customerName: "Нилуфар Холматова", city: "Самарканд", dateLabel: "Февраль 2024", rating: 5, text: "Нашла все книги для подготовки к экзаменам, доставка дошла аккуратно и быстро." },
    { id: "r3", customerName: "Bekhzod Yusupov", city: "Фергана", dateLabel: "Январь 2024", rating: 5, text: "Понравилась удобная фильтрация и то, что после оплаты сразу пришло подтверждение менеджеру." },
    { id: "r4", customerName: "Камола Исмоилова", city: "Бухара", dateLabel: "Март 2024", rating: 5, text: "Подборки выглядят сильно, блог читается легко, а карточки товаров оформлены очень аккуратно." }
  ],
  blogPosts: [
    {
      id: "b1",
      slug: "how-to-build-reading-habit",
      title: { ru: "Как встроить чтение в плотный график", uz: "Band jadvalda o'qishni qanday joylashtirish mumkin", en: "How to build reading into a busy schedule" },
      excerpt: { ru: "Простая система из 5 шагов: от выбора формата до микропривычек, которые реально работают.", uz: "Format tanlashdan boshlab, haqiqatan ishlaydigan kichik odatlar tizimi.", en: "A simple 5-step system, from choosing the right format to micro habits that stick." },
      cover: "https://images.unsplash.com/photo-1455885666463-9d4f9c2baf1d?w=1200&h=800&fit=crop",
      publishedAt: "2026-03-12T08:30:00.000Z",
      readTime: "6 мин",
      category: "Привычки",
      content: [
        { ru: "Первый шаг — не пытаться читать слишком много. Для большинства людей устойчивее работает привычка на 10–15 минут в день, чем намерение читать по книге в неделю.", uz: "Birinchi qadam — birdaniga juda ko'p o'qishga urinmaslik. Ko'pchilik uchun kuniga 10–15 daqiqa odati barqarorroq ishlaydi.", en: "The first step is not trying to read too much at once. For most people, a 10–15 minute daily habit is far more sustainable." },
        { ru: "Второй шаг — заранее решать, что вы будете читать в разных сценариях: дома, в дороге, перед сном, между задачами. Такой список снимает сопротивление выбора.", uz: "Ikkinchi qadam — turli holatlar uchun oldindan nima o'qishni belgilash. Bu tanlashdagi qarshilikni kamaytiradi.", en: "The second step is pre-deciding what you will read in different situations: at home, on the go, before sleep or between tasks." },
        { ru: "Третий шаг — привязать чтение к триггеру. Например: после завтрака 10 страниц, в такси — 15 минут, вечером — одна глава. Чем проще сценарий, тем выше шанс, что он останется с вами надолго.", uz: "Uchinchi qadam — o'qishni aniq triggerga bog'lash. Qanchalik oddiy bo'lsa, shunchalik uzoq davom etadi.", en: "The third step is tying reading to a trigger. The simpler the scenario, the more likely it is to stick." }
      ]
    },
    {
      id: "b2",
      slug: "best-business-books-2026",
      title: { ru: "5 бизнес-книг, которые стоит прочитать в 2026", uz: "2026-yilda o'qishga arziydigan 5 biznes kitob", en: "5 business books worth reading in 2026" },
      excerpt: { ru: "Подборка для предпринимателей, менеджеров и тех, кто хочет усилить мышление о деньгах и системах.", uz: "Tadbirkorlar, menejerlar va moliyaviy fikrlashni kuchaytirmoqchi bo'lganlar uchun tanlov.", en: "A shortlist for founders, managers and anyone wanting stronger thinking about money and systems." },
      cover: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=1200&h=800&fit=crop",
      publishedAt: "2026-03-14T10:15:00.000Z",
      readTime: "7 мин",
      category: "Бизнес",
      content: [
        { ru: "Если вы строите бизнес, важно собирать библиотеку не по громким названиям, а по функциям: продажи, найм, процессы, деньги, личная устойчивость. Хорошая подборка работает как набор инструментов.", uz: "Biznes uchun kutubxona baland nomlarga emas, funksiyalarga ko'ra yig'ilsa foydaliroq bo'ladi.", en: "If you are building a business, build your library by function, not by hype: sales, hiring, processes, money and personal resilience." },
        { ru: "В такой логике «Атомные привычки» отвечает за личную систему, «Богатый папа, бедный папа» — за финансовые модели, а книги по влиянию и мышлению помогают принимать сильные решения в перегруженной среде.", uz: "Shu logikada turli kitoblar turli vazifani yopadi: odatlar, moliyaviy model va qaror sifati.", en: "In that logic, different books cover different jobs: habits, financial models and decision quality." }
      ]
    },
    {
      id: "b3",
      slug: "why-curated-collections-convert-better",
      title: { ru: "Почему подборки продают лучше, чем просто длинный каталог", uz: "Nega to'plamlar uzun katalogdan yaxshiroq ishlaydi", en: "Why curated collections sell better than a long catalog" },
      excerpt: { ru: "Показываем на примере BOOKSHOP, как подборки уменьшают перегрузку выбором и повышают конверсию.", uz: "BOOKSHOP misolida to'plamlar tanlovdagi ortiqcha yukni qanday kamaytirishini ko'rsatamiz.", en: "Using BOOKSHOP as an example, we show how collections reduce choice overload and improve conversion." },
      cover: "https://images.unsplash.com/photo-1516979187457-637abb4f9353?w=1200&h=800&fit=crop",
      publishedAt: "2026-03-18T07:00:00.000Z",
      readTime: "5 мин",
      category: "UX",
      content: [
        { ru: "Когда у пользователя перед глазами сотни карточек, он начинает сравнивать всё со всем и часто откладывает покупку. Подборка работает как готовый сценарий: для ребёнка, для подарка, для бизнеса, для саморазвития.", uz: "Foydalanuvchi oldida juda ko'p variant bo'lsa, u ko'proq ikkilanadi. To'plam esa tayyor ssenariy beradi.", en: "When users see hundreds of cards at once, they compare everything with everything and often postpone buying. A collection works like a ready-made scenario." },
        { ru: "Именно поэтому на главной странице BOOKSHOP подборки стоят рядом с бестселлерами и новинками — они не дублируют каталог, а помогают начать с понятной точки входа.", uz: "Shu sabab BOOKSHOP bosh sahifasida to'plamlar bestseller va yangiliklar yonida turadi.", en: "That is why collections sit next to bestsellers and new arrivals on the BOOKSHOP homepage — they do not duplicate the catalog, they create a clear entry point." }
      ]
    }
  ],
  faqs: [
    {
      id: "f1",
      group: "delivery",
      question: { ru: "Сколько занимает доставка по Ташкенту?", uz: "Toshkent bo'yicha yetkazib berish qancha vaqt oladi?", en: "How long does delivery take in Tashkent?" },
      answer: { ru: "Обычно доставка по Ташкенту занимает от нескольких часов до следующего дня. Для срочных заказов менеджер связывается отдельно.", uz: "Odatda Toshkent bo'yicha yetkazib berish bir necha soatdan keyingi kungacha davom etadi.", en: "Tashkent delivery usually takes from a few hours to the next day." },
    },
    {
      id: "f2",
      group: "delivery",
      question: { ru: "Доставляете ли вы по регионам?", uz: "Viloyatlarga yetkazib berasizlarmi?", en: "Do you deliver to the regions?" },
      answer: { ru: "Да, по всему Узбекистану. Срок зависит от региона и наличия на ближайшем складе, обычно это 1–3 дня.", uz: "Ha, butun O'zbekiston bo'ylab. Odatda 1–3 kun.", en: "Yes, across Uzbekistan. The usual time is 1–3 days depending on stock and destination." },
    },
    {
      id: "f3",
      group: "payment",
      question: { ru: "Как проходит оплата по карте?", uz: "Karta orqali to'lov qanday ishlaydi?", en: "How does card payment work?" },
      answer: { ru: "На этапе оформления заказа клиент получает номер карты, переводит сумму и нажимает кнопку «Я оплатил». После этого в Telegram-бот уходит уведомление менеджеру с деталями заказа.", uz: "Buyurtma paytida karta raqami ko'rsatiladi, mijoz pul o'tkazadi va «To'ladim» tugmasini bosadi.", en: "At checkout the customer sees the card number, transfers the amount and clicks the confirmation button. A Telegram notification is then sent to the manager." },
    },
    {
      id: "f4",
      group: "payment",
      question: { ru: "Можно ли оплатить при получении?", uz: "Yetkazilganda to'lash mumkinmi?", en: "Can I pay on delivery?" },
      answer: { ru: "По умолчанию проект настроен на перевод на карту и ручное подтверждение. Логику оплаты при получении можно добавить отдельным этапом.", uz: "Hozircha loyiha karta orqali o'tkazma va qo'lda tasdiqlashga sozlangan.", en: "The current project is configured for card transfer with manual confirmation. Cash on delivery can be added later." },
    },
    {
      id: "f5",
      group: "returns",
      question: { ru: "Можно ли вернуть книгу?", uz: "Kitobni qaytarish mumkinmi?", en: "Can I return a book?" },
      answer: { ru: "Да, если книга сохранила товарный вид и не имеет следов использования. Обычно срок возврата — до 14 дней.", uz: "Ha, agar kitob yangi holatda bo'lsa va foydalanish izi bo'lmasa, 14 kun ichida qaytarish mumkin.", en: "Yes, if the book is in sellable condition and shows no signs of use. The default return window is 14 days." },
    },
    {
      id: "f6",
      group: "returns",
      question: { ru: "Что делать, если приехала повреждённая книга?", uz: "Agar kitob shikastlangan holda kelsa nima qilish kerak?", en: "What if a book arrives damaged?" },
      answer: { ru: "Нужно связаться с поддержкой и отправить фото. Менеджер предложит обмен или возврат денег, в зависимости от ситуации.", uz: "Qo'llab-quvvatlashga yozib, surat yuborish kerak. Menejer almashtirish yoki qaytarishni taklif qiladi.", en: "Contact support and send photos. A manager will arrange a replacement or refund depending on the case." },
    },
    {
      id: "f7",
      group: "account",
      question: { ru: "Зачем нужен личный кабинет?", uz: "Shaxsiy kabinet nima uchun kerak?", en: "Why do I need a profile?" },
      answer: { ru: "В кабинете сохраняются контактные данные, история заказов, статусы заявок и настройки пользователя. Для повторных заказов это сокращает путь до оформления.", uz: "Kabinetda aloqa ma'lumotlari va buyurtmalar tarixi saqlanadi.", en: "The profile stores customer data, order history and request statuses for faster repeat checkouts." },
    },
    {
      id: "f8",
      group: "account",
      question: { ru: "Работает ли вход через Google?", uz: "Google orqali kirish ishlaydimi?", en: "Does Google sign-in work?" },
      answer: { ru: "Да, архитектура уже подготовлена. Нужно только заполнить Google Client ID, Secret и Redirect URI в .env.", uz: "Ha, arxitektura tayyor. .env faylida Google Client ID, Secret va Redirect URI ko'rsatish kifoya.", en: "Yes, the architecture is ready. You only need to fill in Google Client ID, Secret and Redirect URI in the .env file." },
    }
  ],
};
